import {useState,useEffect,useRef, Component, type ReactNode} from 'react';
import {Compass,Home,CalendarDays,Target,Menu,Plus,ArrowRight,Heart,Wallet,Book,Gamepad,Sun,Moon,CheckCircle2,RefreshCw,LogOut,ChevronRight,X,Bell,Calendar,HeartPulse,Rocket,Mail,BookOpenText,BellRing,LayoutGrid,CircleAlert,CloudSunRain,Cog} from 'lucide-react';
import type {Snapshot,Command,CommandEnvelope,Block,Task} from '../shared/types';
import {dateKey,addDays} from '../shared/dates';
import * as api from './api';
import {SetupPage} from './SetupPage';
import {MissingPage} from './MissingPage';
import {Modal,type PageProps} from './ui';
import {TaskEditor,ResolveDialog,SchedulePage,StartDayDialog,EndDayDialog,TemplatesPage} from './planning';
import {GoalsPage,HealthPage,RocketPage,MoneyPage,HistoryPage,RemindersPage,WeatherPage,SettingsPage} from './features';

import {HomePage} from './HomePage';
import {TaskListPage} from './TaskListPage';

export type View='home'|'schedule'|'goals'|'more'|'health'|'rocket'|'money'|'history'|'reminders'|'weather'|'settings'|'templates'|'missing'|'tasks';
const navigation=[{id:'home' as View,label:'Home',icon:Home},{id:'schedule' as View,label:'Schedule',icon:CalendarDays},{id:'goals' as View,label:'Goals',icon:Target},{id:'more' as View,label:'More',icon:Menu}];
const destinations=[{id:'tasks' as View,label:'Task list',detail:'Everything waiting for a day',icon:CheckCircle2},{id:'health' as View,label:'Health',detail:'Sleep, movement, meals and weight',icon:HeartPulse},{id:'rocket' as View,label:'Rocket League',detail:'Practice with intention',icon:Rocket},{id:'money' as View,label:'Envelopes',detail:'Personal and company funds',icon:Mail},{id:'history' as View,label:'Journal & history',detail:'Your days, worth remembering',icon:BookOpenText},{id:'reminders' as View,label:'Reminders',detail:'Keep something in view',icon:BellRing},{id:'templates' as View,label:'Day templates',detail:'A familiar rhythm to start from',icon:LayoutGrid},{id:'missing' as View,label:'Review missing data',detail:'A quiet catch-up, at your pace',icon:CircleAlert},{id:'weather' as View,label:'Weather',detail:'Home and the places you work',icon:CloudSunRain},{id:'settings' as View,label:'Settings',detail:'Personal preferences',icon:Cog}];
const views=new Set(['home','schedule','goals','more',...destinations.map(d=>d.id)]);
function route():View{const p=location.hash.slice(2).split('?')[0];return views.has(p)?p as View:'home';}
class Boundary extends Component<{children:ReactNode},{error:boolean}>{state={error:false};static getDerivedStateFromError(){return{error:true};}render(){return this.state.error?<div className="signin"><h1>A screen needs a fresh start.</h1><p>Your saved records are still on the server.</p><button onClick={()=>location.reload()}>Reload Caminos</button></div>:this.props.children;}}
export default function App(){return <Boundary><Caminos/></Boundary>;}
function Caminos(){
 const [setupToken]=useState(()=>new URLSearchParams(location.hash.split('?')[1]??'').get('token'));
 useEffect(()=>{if(setupToken)history.replaceState(null,'','#/setup');},[setupToken]);
 const [state,setState]=useState<Snapshot|null>(null);const stateRef=useRef<Snapshot|null>(null);const [auth,setAuth]=useState<boolean|null>(null);const [ownerConfigured,setConfigured]=useState(true);const [password,setPassword]=useState('');const [busy,setBusy]=useState(false);const busyRef=useRef(false);const [error,setError]=useState('');const [notice,setNotice]=useState('');const [online,setOnline]=useState(true);const [view,setView]=useState<View>(route);const [now,setNow]=useState(new Date().toISOString());const clockRef=useRef({server:Date.now(),mono:performance.now()});const uncertain=useRef<CommandEnvelope|null>(null);const retryCompletion=useRef<((ok:boolean)=>void)|null>(null);const [unknown,setUnknown]=useState(false);const [addSheet,setAddSheet]=useState(false);const [editor,setEditor]=useState<{task?:Task;block?:Block;appointment?:boolean}|null>(null);const [resolve,setResolve]=useState<Block|null>(null);const [dayDialog,setDayDialog]=useState<'start'|'end'|null>(null);const [addPage,setAddPage]=useState<{id:View;kind?:string;key:number}|null>(null);const [scheduleDate,setScheduleDate]=useState<string|undefined>();
 const accept=(s:Snapshot)=>{if(!stateRef.current||s.revision>=stateRef.current.revision){stateRef.current=s;setState(s);setNow(s.serverNow);clockRef.current={server:Date.parse(s.serverNow),mono:performance.now()};setOnline(true);}};
 const refresh=async()=>{try{accept(await api.snapshot());}catch(e){if(e instanceof api.ApiError&&e.status===401){stateRef.current=null;setState(null);setAuth(false);}else setOnline(false);}};
 useEffect(()=>{let alive=true;(async()=>{try{const s=await api.session();if(!alive)return;setAuth(s.authenticated);setConfigured((s as {ownerConfigured?:boolean}).ownerConfigured!==false);if(s.authenticated)await refresh();}catch(e){setError((e as Error).message);setAuth(false);}})();const tick=setInterval(()=>setNow(new Date(clockRef.current.server+performance.now()-clockRef.current.mono).toISOString()),1000);const hash=()=>setView(route());window.addEventListener('hashchange',hash);return()=>{alive=false;clearInterval(tick);window.removeEventListener('hashchange',hash);};},[]);
 useEffect(()=>{if(!auth)return;const poll=setInterval(()=>{if(!document.hidden&&!busyRef.current)void refresh();},15000);const focus=()=>{if(!document.hidden&&!busyRef.current)void refresh();};document.addEventListener('visibilitychange',focus);window.addEventListener('focus',focus);return()=>{clearInterval(poll);document.removeEventListener('visibilitychange',focus);window.removeEventListener('focus',focus);};},[auth]);
 async function run(command:Command){command=JSON.parse(JSON.stringify(command,(key,value)=>key==='createdAt'||key==='updatedAt'?undefined:value)) as Command;if(!stateRef.current||busyRef.current)return false;if(uncertain.current){setError('A save still needs verification. Use Retry save before making another change.');window.dispatchEvent(new CustomEvent('caminos-error',{detail:{message:'A save still needs verification. Retry it first.',uncertain:true}}));return false;}const envelope={requestId:crypto.randomUUID(),baseRevision:stateRef.current.revision,command};return execute(envelope);}
 async function execute(envelope:CommandEnvelope){busyRef.current=true;setBusy(true);setError('');try{const result=await api.mutate(envelope);accept(result.snapshot);uncertain.current=null;setUnknown(false);setNotice('Saved');window.dispatchEvent(new Event('caminos-saved'));retryCompletion.current?.(true);retryCompletion.current=null;return true;}catch(e){const err=e as api.ApiError;setError(err.message);window.dispatchEvent(new CustomEvent('caminos-error',{detail:{message:err.message,uncertain:!err.status||err.status>=500}}));if(!err.status||err.status>=500){uncertain.current=envelope;setUnknown(true);if(!retryCompletion.current)return new Promise<boolean>(resolve=>{retryCompletion.current=resolve;});return false;}uncertain.current=null;setUnknown(false);retryCompletion.current?.(false);retryCompletion.current=null;if(err.status===409)await refresh();if(err.status===401){setAuth(false);setState(null);stateRef.current=null;}return false;}finally{busyRef.current=false;setBusy(false);}}
 function go(id:View,kind?:string){setAddPage(kind?{id,kind,key:Date.now()}:null);location.hash=`/${id}`;setView(id);setAddSheet(false);document.querySelector('.content')?.scrollTo(0,0);}
 const pickAdd=(kind:string)=>{setAddSheet(false);if(kind==='task'||kind==='appointment'){setEditor({appointment:kind==='appointment'});return;}const map:Record<string,View>={goal:'goals',health:'health',food:'health',rocket:'rocket',journal:'history',reminder:'reminders',envelope:'money'};go(map[kind],kind);};
 useEffect(()=>{const retry=()=>{if(uncertain.current&&!busyRef.current)void execute(uncertain.current);};window.addEventListener('caminos-retry',retry);return()=>window.removeEventListener('caminos-retry',retry);},[]);
 if(auth===null)return <div className="signin"><Compass size={40}/><h1>Caminos</h1><p>Opening your day…</p></div>;
 if(!auth&&setupToken&&!ownerConfigured)return <SetupPage token={setupToken} onReady={async()=>{await api.session();setConfigured(true);setAuth(true);await refresh();}}/>;
 if(!auth)return <main className="signin"><div className="brand-mark"><Compass size={30}/></div><p className="eyebrow">Your life. A little clearer.</p><h1>Welcome to Caminos.</h1><p className="muted">A private place for your days, goals and everything that matters.</p><form className="stack" onSubmit={async e=>{e.preventDefault();setBusy(true);setError('');try{await api.login(password);setPassword('');setAuth(true);await refresh();}catch(e){setError((e as Error).message);}finally{setBusy(false);}}}><label className="field"><span>Your password</span><input type="password" autoComplete="current-password" value={password} onChange={e=>setPassword(e.target.value)} required/></label><button disabled={busy||!ownerConfigured} className="primary">{busy?'Signing in…':'Open my day'}<ArrowRight size={18}/></button></form>{!ownerConfigured&&<p className="notice">Your private account needs its initial setup before sign-in. Use the owner setup command on the server.</p>}{error&&<p role="alert" className="notice warning">{error}</p>}<p className="suite-signature">by Morgan</p></main>;
 if(!state)return <main className="signin"><h1>Opening your day…</h1>{error&&<p>{error}</p>}<button onClick={refresh}>Try again</button></main>;
 const page:PageProps={state,now,run,add:addPage?.id===view,addKind:addPage?.kind};const activeDay=state.days.find(d=>!d.endedAt);const orderedNavigation=[...navigation].sort((a,b)=>{const order:readonly string[]=state.settings.navOrder??['home','schedule','goals','more'];return order.indexOf(a.id)-order.indexOf(b.id);});
 return <div className="app redesign-v2" data-view={view}><header className={`brand-bar ${['home','schedule','goals','health','history','money','more'].includes(view)?'':'brand-bar-secondary'}`}><a href="#/home" className="brand" onClick={()=>go('home')}><span className="brand-mark"><Compass size={23}/></span><span>Caminos<small>by Morgan</small></span></a>{view==='more'?<span className="more-signature">BY MORGAN</span>:<button className={`day-toggle ${activeDay?'':'day-start'}`} onClick={()=>setDayDialog(activeDay?'end':'start')}>{activeDay?<Moon size={17}/>:<Sun size={17}/>}<span>{activeDay?'End day':'Start day'}</span></button>}</header><aside className="sidebar"><p className="eyebrow">YOUR PERSONAL SPACE</p>{orderedNavigation.map(({id,label,icon:Icon})=><button key={id} className={view===id?'selected':''} onClick={()=>go(id)}><Icon size={19}/>{label}</button>)}<div className="sidebar-divider"/>{destinations.filter(d=>['health','money','history','rocket'].includes(d.id)).map(({id,label,icon:Icon})=><button key={id} className={view===id?'selected':''} onClick={()=>go(id)}><Icon size={18}/>{label}</button>)}<p className="sidebar-footer">One moment at a time.</p></aside><main id="main" className="content"><div className={`page ${view==='schedule'?'schedule-page':''}`} key={`${view}-${addPage?.key??''}`}><div className="connection">{!online&&<div className="notice warning">Connection paused. Saved information stays on the server.<button onClick={refresh}>Reconnect</button></div>}{error&&<div role="alert" className="notice warning"><span>{error}</span><button aria-label="Dismiss error" className="icon-button" onClick={()=>setError('')}><X size={16}/></button></div>}{unknown&&<div className="notice"><span>Check whether your last save reached the server.</span><button disabled={busy} onClick={()=>uncertain.current&&execute(uncertain.current)}>Retry save</button></div>}</div>
 {view==='home'?<HomePage {...page} go={go} onResolve={setResolve} onStart={()=>setDayDialog('start')}/>:view==='schedule'?<SchedulePage {...page} initialDate={scheduleDate} onResolve={setResolve}/>:view==='goals'?<GoalsPage {...page}/>:view==='health'?<HealthPage {...page}/>:view==='rocket'?<RocketPage {...page}/>:view==='money'?<MoneyPage {...page}/>:view==='history'?<HistoryPage {...page}/>:view==='reminders'?<RemindersPage {...page}/>:view==='weather'?<WeatherPage {...page}/>:view==='settings'?<SettingsPage {...page}/>:view==='templates'?<TemplatesPage {...page}/>:view==='missing'?<MissingPage {...page}/>:view==='tasks'?<TaskListPage {...page} onEdit={setEditor}/>:<div className="v2-more"><h1 className="sr-only">More</h1><div className="destination-grid">{destinations.map(({id,label,icon:Icon})=><button key={id} className="destination" onClick={()=>go(id)}><span className="destination-icon"><Icon size={20}/></span><span><strong>{label}</strong></span>{id==='tasks'||id==='rocket'?<span className="destination-badge">{id==='tasks'?'TASKS':'LOG'}</span>:<ChevronRight size={18}/>}</button>)}</div><div className="account-actions"><button onClick={refresh}><RefreshCw size={17}/>Refresh</button><a href="/api/export" download>Export my records</a><button onClick={async()=>{await api.logout();setState(null);stateRef.current=null;setAuth(false);await api.session();}}><LogOut size={17}/>Sign out</button></div></div>}
 </div></main><button className="add-button" onClick={()=>setAddSheet(true)}><Plus size={23}/><span>Add</span></button><nav className="bottom-nav" aria-label="Main navigation">{orderedNavigation.map(({id,label,icon:Icon})=><a href={`#/${id}`} key={id} aria-current={(view===id||(id==='more'&&!['home','schedule','goals'].includes(view)))?'page':undefined} className={(view===id||(id==='more'&&!['home','schedule','goals'].includes(view)))?'selected':''} onClick={e=>{e.preventDefault();go(id);}}><Icon size={22}/><span>{label}</span></a>)}</nav>{notice&&<div className="save-toast" role="status"><CheckCircle2 size={16}/>{notice}<button aria-label="Dismiss saved message" onClick={()=>setNotice('')}><X size={15}/></button></div>}
 {addSheet&&<Modal className="add-menu-sheet" title="Make a little room." onClose={()=>setAddSheet(false)}><div className="add-grid">{[{id:'task',label:'Task',icon:CheckCircle2},{id:'appointment',label:'Appointment',icon:Calendar},{id:'goal',label:'Goal',icon:Target},{id:'health',label:'Health',icon:Heart},{id:'food',label:'Food',icon:Sun},{id:'rocket',label:'Rocket League',icon:Gamepad},{id:'journal',label:'Journal',icon:Book},{id:'reminder',label:'Reminder',icon:Bell},{id:'envelope',label:'Envelope',icon:Wallet}].map(({id,label,icon:Icon})=><button key={id} onClick={()=>pickAdd(id)}><span className="add-tile-icon"><Icon size={22}/></span><span>{label}</span></button>)}</div></Modal>}{editor&&<TaskEditor {...page} {...editor} onClose={()=>setEditor(null)}/>} {dayDialog==='start'&&<StartDayDialog {...page} onClose={()=>setDayDialog(null)}/>} {dayDialog==='end'&&activeDay&&<EndDayDialog {...page} day={activeDay} onClose={()=>setDayDialog(null)} onResolve={setResolve} onPlanTomorrow={()=>{setScheduleDate(addDays(dateKey(now),1));setDayDialog(null);go('schedule');}}/>}{resolve&&<ResolveDialog block={state.blocks.find(b=>b.id===resolve.id)??resolve} now={now} run={run} onClose={()=>setResolve(null)}/>}</div>;
}
