import {useState} from 'react';
import {ArrowRight,CheckCircle2} from 'lucide-react';
import type {LogKind} from '../shared/types';
import {missingItems} from '../shared/selectors';
import {dateKey,localInstant} from '../shared/dates';
import {snapshot} from './api';
import {LogEditor} from './features/health';
import {Modal,Field,DateTimeField,Empty,type PageProps} from './ui';
export function MissingPage({state,now,run}:PageProps){
 const [date,setDate]=useState(dateKey(now));const [skipped,setSkipped]=useState<string[]>([]);const [editing,setEditing]=useState<string|null>(null);const [value,setValue]=useState('');const [wake,setWake]=useState(now);const [busy,setBusy]=useState(false);
 const items=missingItems(state,date).filter(i=>!skipped.includes(i.key));const item=items[0];const day=state.days.find(d=>d.date===date);const at=date===dateKey(now)?now:localInstant(date,'12:00');
 async function save(e:React.FormEvent){e.preventDefault();setBusy(true);try{let id=day?.id;if(!id){if(!await run({type:'day.save',date,summary:'',journal:''}))return;id=(await snapshot()).days.find(d=>d.date===date)?.id;}if(!id)return;const okay=editing==='journal'?await run({type:'day.save',id,summary:day?.summary??'',journal:value,note:day?.note??''}):await run({type:'day.checkin',id,...(editing==='start'?{wakeAt:wake}:editing==='mood'?{mood:Number(value)}:{energy:Number(value)})});if(okay){setEditing(null);setValue('');}}finally{setBusy(false);}}
 return <><header className="page-heading"><h1>A quiet catch-up.</h1><p>One missing entry at a time. Skip anything you don’t know.</p></header><Field label="Review date"><input type="date" max={dateKey(now)} value={date} onChange={e=>{if(e.target.value){setDate(e.target.value);setSkipped([]);}}}/></Field><section className="card">{item?<><p className="eyebrow">{items.length} remaining</p><h2>{item.label} is not recorded</h2><p className="muted">Add what you know for {date}. A missing entry is never counted as zero.</p><div className="inline-actions"><button className="primary" onClick={()=>{setEditing(item.key);setValue('');setWake(at);}}>Add information<ArrowRight size={17}/></button><button onClick={()=>setSkipped([...skipped,item.key])}>Skip for now</button></div></>:<Empty><CheckCircle2 size={21}/> All caught up for this review.</Empty>}</section><p className="muted">Workouts and practice are optional activities. Empty days do not create missing-activity alerts.</p>{editing&&['sleep','weight','steps','food'].includes(editing)?<LogEditor kind={editing as LogKind} now={at} run={run} close={()=>setEditing(null)}/>:editing&&<Modal title={`Add ${item?.label.toLowerCase()??'entry'}`} onClose={()=>setEditing(null)}><form className="stack" onSubmit={save}>{editing==='start'?<DateTimeField label="Woke up" value={wake} onChange={setWake}/>:editing==='journal'?<Field label="Your journal"><textarea required rows={7} value={value} onChange={e=>setValue(e.target.value)}/></Field>:<Field label={editing==='mood'?'Mood':'Energy'}><select required value={value} onChange={e=>setValue(e.target.value)}><option value="">Choose a rating</option>{[1,2,3,4,5].map(n=><option key={n} value={n}>{n} / 5</option>)}</select></Field>}<button disabled={busy} className="primary">Save entry</button></form></Modal>}</>;
}
